# Generated by Django 5.1.3 on 2025-01-31 08:56

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='property_videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
