# Generated by Django 5.1.3 on 2024-12-16 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('REFERRAL', 'Referral Bonus'), ('PERFORMANCE', 'Performance Bonus')], max_length=20)),
                ('claimed', models.BooleanField(default=False)),
                ('date_claimed', models.DateTimeField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
                'ordering': ['-awarded_at'],
            },
        ),
    ]
